package com.shoppilist.shared.domain

/**
 * Curated location reference data for the registration/profile address form: states/
 * provinces per country and major cities per state. City coverage is intentionally major-
 * cities-only -- the address form offers a free-text "Other" fallback for unlisted places.
 * Generated from a one-off script (not committed).
 */
object LocationData {
    /** ISO2 country code -> ordered list of states/provinces. */
    val statesByCountry: Map<String, List<String>> = mapOf(
        "IN" to listOf("Andhra Pradesh", "Assam", "Bihar", "Chhattisgarh", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Odisha", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana", "Uttar Pradesh", "Uttarakhand", "West Bengal", "Jammu and Kashmir", "Chandigarh"),
        "US" to listOf("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Florida", "Georgia", "Illinois", "Massachusetts", "Michigan", "Nevada", "New Jersey", "New York", "North Carolina", "Ohio", "Oregon", "Pennsylvania", "Texas", "Virginia", "Washington"),
        "GB" to listOf("England", "Scotland", "Wales", "Northern Ireland"),
        "AE" to listOf("Abu Dhabi", "Dubai", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"),
        "DE" to listOf("Bavaria", "Berlin", "Hamburg", "Hesse", "North Rhine-Westphalia", "Baden-Wurttemberg", "Saxony", "Lower Saxony"),
        "AU" to listOf("New South Wales", "Victoria", "Queensland", "Western Australia", "South Australia", "Tasmania", "Australian Capital Territory", "Northern Territory"),
        "SG" to listOf("Central Region", "East Region", "North Region", "North-East Region", "West Region"),
        "BR" to listOf("Sao Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia", "Parana", "Rio Grande do Sul", "Pernambuco", "Distrito Federal"),
        "FR" to listOf("Ile-de-France", "Provence-Alpes-Cote d'Azur", "Auvergne-Rhone-Alpes", "Occitanie", "Nouvelle-Aquitaine", "Grand Est", "Hauts-de-France", "Brittany"),
        "CN" to listOf("Beijing", "Shanghai", "Guangdong", "Zhejiang", "Jiangsu", "Sichuan", "Hubei", "Shandong"),
        "ID" to listOf("Jakarta", "West Java", "East Java", "Central Java", "Bali", "Banten", "North Sumatra"),
        "IT" to listOf("Lazio", "Lombardy", "Campania", "Sicily", "Veneto", "Piedmont", "Tuscany", "Emilia-Romagna"),
        "JP" to listOf("Tokyo", "Osaka", "Kanagawa", "Aichi", "Hokkaido", "Fukuoka", "Kyoto", "Hyogo"),
        "MX" to listOf("Mexico City", "Jalisco", "Nuevo Leon", "Puebla", "Baja California", "Quintana Roo", "Guanajuato"),
        "NG" to listOf("Lagos", "Abuja (FCT)", "Rivers", "Kano", "Oyo", "Kaduna", "Enugu"),
        "SA" to listOf("Riyadh", "Makkah", "Eastern Province", "Madinah", "Asir", "Qassim"),
        "ZA" to listOf("Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape", "Free State", "Mpumalanga"),
        "KR" to listOf("Seoul", "Busan", "Incheon", "Gyeonggi", "Daegu", "Daejeon", "Gwangju"),
        "ES" to listOf("Madrid", "Catalonia", "Andalusia", "Valencia", "Basque Country", "Galicia"),
    )

    /** "ISO2|State" -> ordered list of major cities. */
    val citiesByState: Map<String, List<String>> = mapOf(
        "IN|Andhra Pradesh" to listOf("Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Tirupati", "Kurnool"),
        "IN|Assam" to listOf("Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"),
        "IN|Bihar" to listOf("Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga"),
        "IN|Chhattisgarh" to listOf("Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"),
        "IN|Delhi" to listOf("New Delhi", "Delhi", "Dwarka", "Rohini", "Saket"),
        "IN|Goa" to listOf("Panaji", "Margao", "Vasco da Gama", "Mapusa"),
        "IN|Gujarat" to listOf("Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar", "Bhavnagar"),
        "IN|Haryana" to listOf("Gurugram", "Faridabad", "Panipat", "Ambala", "Karnal", "Hisar"),
        "IN|Himachal Pradesh" to listOf("Shimla", "Dharamshala", "Solan", "Mandi", "Kullu"),
        "IN|Jharkhand" to listOf("Ranchi", "Jamshedpur", "Dhanbad", "Bokaro"),
        "IN|Karnataka" to listOf("Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belagavi", "Davangere"),
        "IN|Kerala" to listOf("Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"),
        "IN|Madhya Pradesh" to listOf("Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"),
        "IN|Maharashtra" to listOf("Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad"),
        "IN|Manipur" to listOf("Imphal", "Thoubal"),
        "IN|Meghalaya" to listOf("Shillong", "Tura"),
        "IN|Odisha" to listOf("Bhubaneswar", "Cuttack", "Rourkela", "Berhampur"),
        "IN|Punjab" to listOf("Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Mohali"),
        "IN|Rajasthan" to listOf("Jaipur", "Jodhpur", "Udaipur", "Kota", "Ajmer", "Bikaner"),
        "IN|Tamil Nadu" to listOf("Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"),
        "IN|Telangana" to listOf("Hyderabad", "Warangal", "Nizamabad", "Karimnagar"),
        "IN|Uttar Pradesh" to listOf("Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Noida", "Prayagraj"),
        "IN|Uttarakhand" to listOf("Dehradun", "Haridwar", "Nainital", "Rishikesh"),
        "IN|West Bengal" to listOf("Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri"),
        "IN|Jammu and Kashmir" to listOf("Srinagar", "Jammu"),
        "IN|Chandigarh" to listOf("Chandigarh"),
        "US|Alabama" to listOf("Birmingham", "Montgomery", "Huntsville", "Mobile"),
        "US|Alaska" to listOf("Anchorage", "Fairbanks", "Juneau"),
        "US|Arizona" to listOf("Phoenix", "Tucson", "Mesa", "Scottsdale", "Tempe"),
        "US|Arkansas" to listOf("Little Rock", "Fayetteville", "Fort Smith"),
        "US|California" to listOf("Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento", "Oakland", "Fresno"),
        "US|Colorado" to listOf("Denver", "Colorado Springs", "Aurora", "Boulder"),
        "US|Connecticut" to listOf("Hartford", "New Haven", "Stamford", "Bridgeport"),
        "US|Florida" to listOf("Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"),
        "US|Georgia" to listOf("Atlanta", "Savannah", "Augusta", "Athens"),
        "US|Illinois" to listOf("Chicago", "Aurora", "Naperville", "Springfield"),
        "US|Massachusetts" to listOf("Boston", "Cambridge", "Worcester", "Springfield"),
        "US|Michigan" to listOf("Detroit", "Grand Rapids", "Ann Arbor", "Lansing"),
        "US|Nevada" to listOf("Las Vegas", "Reno", "Henderson"),
        "US|New Jersey" to listOf("Newark", "Jersey City", "Trenton", "Princeton"),
        "US|New York" to listOf("New York City", "Buffalo", "Rochester", "Albany", "Syracuse"),
        "US|North Carolina" to listOf("Charlotte", "Raleigh", "Durham", "Greensboro"),
        "US|Ohio" to listOf("Columbus", "Cleveland", "Cincinnati", "Dayton"),
        "US|Oregon" to listOf("Portland", "Eugene", "Salem", "Bend"),
        "US|Pennsylvania" to listOf("Philadelphia", "Pittsburgh", "Allentown", "Harrisburg"),
        "US|Texas" to listOf("Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso"),
        "US|Virginia" to listOf("Virginia Beach", "Richmond", "Arlington", "Norfolk"),
        "US|Washington" to listOf("Seattle", "Spokane", "Tacoma", "Bellevue"),
        "GB|England" to listOf("London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Bristol", "Sheffield", "Newcastle", "Nottingham", "Leicester"),
        "GB|Scotland" to listOf("Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness"),
        "GB|Wales" to listOf("Cardiff", "Swansea", "Newport", "Wrexham"),
        "GB|Northern Ireland" to listOf("Belfast", "Londonderry", "Lisburn"),
        "AE|Abu Dhabi" to listOf("Abu Dhabi", "Al Ain", "Madinat Zayed"),
        "AE|Dubai" to listOf("Dubai", "Jebel Ali"),
        "AE|Sharjah" to listOf("Sharjah", "Khor Fakkan"),
        "AE|Ajman" to listOf("Ajman"),
        "AE|Ras Al Khaimah" to listOf("Ras Al Khaimah"),
        "AE|Fujairah" to listOf("Fujairah"),
        "AE|Umm Al Quwain" to listOf("Umm Al Quwain"),
        "DE|Bavaria" to listOf("Munich", "Nuremberg", "Augsburg", "Regensburg"),
        "DE|Berlin" to listOf("Berlin"),
        "DE|Hamburg" to listOf("Hamburg"),
        "DE|Hesse" to listOf("Frankfurt", "Wiesbaden", "Darmstadt", "Kassel"),
        "DE|North Rhine-Westphalia" to listOf("Cologne", "Dusseldorf", "Dortmund", "Essen", "Bonn"),
        "DE|Baden-Wurttemberg" to listOf("Stuttgart", "Mannheim", "Karlsruhe", "Freiburg"),
        "DE|Saxony" to listOf("Dresden", "Leipzig", "Chemnitz"),
        "DE|Lower Saxony" to listOf("Hanover", "Braunschweig", "Osnabruck"),
        "AU|New South Wales" to listOf("Sydney", "Newcastle", "Wollongong"),
        "AU|Victoria" to listOf("Melbourne", "Geelong", "Ballarat"),
        "AU|Queensland" to listOf("Brisbane", "Gold Coast", "Cairns", "Townsville"),
        "AU|Western Australia" to listOf("Perth", "Fremantle", "Bunbury"),
        "AU|South Australia" to listOf("Adelaide", "Mount Gambier"),
        "AU|Tasmania" to listOf("Hobart", "Launceston"),
        "AU|Australian Capital Territory" to listOf("Canberra"),
        "AU|Northern Territory" to listOf("Darwin", "Alice Springs"),
        "SG|Central Region" to listOf("Singapore (Central)", "Orchard", "Bishan", "Toa Payoh"),
        "SG|East Region" to listOf("Bedok", "Tampines", "Pasir Ris", "Changi"),
        "SG|North Region" to listOf("Woodlands", "Yishun", "Sembawang"),
        "SG|North-East Region" to listOf("Serangoon", "Hougang", "Punggol", "Sengkang"),
        "SG|West Region" to listOf("Jurong", "Clementi", "Bukit Batok", "Choa Chu Kang"),
        "BR|Sao Paulo" to listOf("Sao Paulo", "Campinas", "Santos", "Guarulhos"),
        "BR|Rio de Janeiro" to listOf("Rio de Janeiro", "Niteroi", "Petropolis"),
        "BR|Minas Gerais" to listOf("Belo Horizonte", "Uberlandia", "Contagem"),
        "BR|Bahia" to listOf("Salvador", "Feira de Santana"),
        "BR|Parana" to listOf("Curitiba", "Londrina", "Maringa"),
        "BR|Rio Grande do Sul" to listOf("Porto Alegre", "Caxias do Sul"),
        "BR|Pernambuco" to listOf("Recife", "Olinda"),
        "BR|Distrito Federal" to listOf("Brasilia"),
        "FR|Ile-de-France" to listOf("Paris", "Versailles", "Boulogne-Billancourt", "Saint-Denis"),
        "FR|Provence-Alpes-Cote d'Azur" to listOf("Marseille", "Nice", "Toulon", "Cannes"),
        "FR|Auvergne-Rhone-Alpes" to listOf("Lyon", "Grenoble", "Saint-Etienne", "Annecy"),
        "FR|Occitanie" to listOf("Toulouse", "Montpellier", "Nimes"),
        "FR|Nouvelle-Aquitaine" to listOf("Bordeaux", "Limoges", "Pau"),
        "FR|Grand Est" to listOf("Strasbourg", "Reims", "Metz", "Nancy"),
        "FR|Hauts-de-France" to listOf("Lille", "Amiens", "Roubaix"),
        "FR|Brittany" to listOf("Rennes", "Brest", "Quimper"),
        "CN|Beijing" to listOf("Beijing"),
        "CN|Shanghai" to listOf("Shanghai"),
        "CN|Guangdong" to listOf("Guangzhou", "Shenzhen", "Dongguan", "Foshan"),
        "CN|Zhejiang" to listOf("Hangzhou", "Ningbo", "Wenzhou"),
        "CN|Jiangsu" to listOf("Nanjing", "Suzhou", "Wuxi"),
        "CN|Sichuan" to listOf("Chengdu", "Mianyang"),
        "CN|Hubei" to listOf("Wuhan", "Yichang"),
        "CN|Shandong" to listOf("Jinan", "Qingdao"),
        "ID|Jakarta" to listOf("Jakarta", "South Jakarta", "West Jakarta"),
        "ID|West Java" to listOf("Bandung", "Bekasi", "Depok", "Bogor"),
        "ID|East Java" to listOf("Surabaya", "Malang", "Sidoarjo"),
        "ID|Central Java" to listOf("Semarang", "Solo", "Magelang"),
        "ID|Bali" to listOf("Denpasar", "Kuta", "Ubud"),
        "ID|Banten" to listOf("Tangerang", "Serang"),
        "ID|North Sumatra" to listOf("Medan", "Binjai"),
        "IT|Lazio" to listOf("Rome", "Latina"),
        "IT|Lombardy" to listOf("Milan", "Bergamo", "Brescia", "Monza"),
        "IT|Campania" to listOf("Naples", "Salerno"),
        "IT|Sicily" to listOf("Palermo", "Catania", "Messina"),
        "IT|Veneto" to listOf("Venice", "Verona", "Padua"),
        "IT|Piedmont" to listOf("Turin", "Novara"),
        "IT|Tuscany" to listOf("Florence", "Pisa", "Siena"),
        "IT|Emilia-Romagna" to listOf("Bologna", "Parma", "Modena"),
        "JP|Tokyo" to listOf("Tokyo", "Shibuya", "Shinjuku"),
        "JP|Osaka" to listOf("Osaka", "Sakai"),
        "JP|Kanagawa" to listOf("Yokohama", "Kawasaki"),
        "JP|Aichi" to listOf("Nagoya", "Toyota"),
        "JP|Hokkaido" to listOf("Sapporo", "Hakodate"),
        "JP|Fukuoka" to listOf("Fukuoka", "Kitakyushu"),
        "JP|Kyoto" to listOf("Kyoto"),
        "JP|Hyogo" to listOf("Kobe", "Himeji"),
        "MX|Mexico City" to listOf("Mexico City"),
        "MX|Jalisco" to listOf("Guadalajara", "Zapopan", "Puerto Vallarta"),
        "MX|Nuevo Leon" to listOf("Monterrey", "San Pedro"),
        "MX|Puebla" to listOf("Puebla", "Cholula"),
        "MX|Baja California" to listOf("Tijuana", "Mexicali", "Ensenada"),
        "MX|Quintana Roo" to listOf("Cancun", "Playa del Carmen", "Tulum"),
        "MX|Guanajuato" to listOf("Leon", "Guanajuato", "Irapuato"),
        "NG|Lagos" to listOf("Lagos", "Ikeja", "Lekki", "Ikorodu"),
        "NG|Abuja (FCT)" to listOf("Abuja", "Gwagwalada"),
        "NG|Rivers" to listOf("Port Harcourt", "Bonny"),
        "NG|Kano" to listOf("Kano"),
        "NG|Oyo" to listOf("Ibadan", "Ogbomosho"),
        "NG|Kaduna" to listOf("Kaduna", "Zaria"),
        "NG|Enugu" to listOf("Enugu", "Nsukka"),
        "SA|Riyadh" to listOf("Riyadh", "Diriyah"),
        "SA|Makkah" to listOf("Jeddah", "Mecca", "Taif"),
        "SA|Eastern Province" to listOf("Dammam", "Dhahran", "Khobar", "Jubail"),
        "SA|Madinah" to listOf("Medina", "Yanbu"),
        "SA|Asir" to listOf("Abha", "Khamis Mushait"),
        "SA|Qassim" to listOf("Buraidah", "Unaizah"),
        "ZA|Gauteng" to listOf("Johannesburg", "Pretoria", "Soweto", "Sandton"),
        "ZA|Western Cape" to listOf("Cape Town", "Stellenbosch", "George"),
        "ZA|KwaZulu-Natal" to listOf("Durban", "Pietermaritzburg"),
        "ZA|Eastern Cape" to listOf("Gqeberha", "East London"),
        "ZA|Free State" to listOf("Bloemfontein", "Welkom"),
        "ZA|Mpumalanga" to listOf("Nelspruit", "Witbank"),
        "KR|Seoul" to listOf("Seoul"),
        "KR|Busan" to listOf("Busan"),
        "KR|Incheon" to listOf("Incheon"),
        "KR|Gyeonggi" to listOf("Suwon", "Seongnam", "Goyang", "Yongin"),
        "KR|Daegu" to listOf("Daegu"),
        "KR|Daejeon" to listOf("Daejeon"),
        "KR|Gwangju" to listOf("Gwangju"),
        "ES|Madrid" to listOf("Madrid", "Alcala de Henares", "Getafe"),
        "ES|Catalonia" to listOf("Barcelona", "Girona", "Tarragona", "Sabadell"),
        "ES|Andalusia" to listOf("Seville", "Malaga", "Granada", "Cordoba"),
        "ES|Valencia" to listOf("Valencia", "Alicante", "Castellon"),
        "ES|Basque Country" to listOf("Bilbao", "San Sebastian", "Vitoria-Gasteiz"),
        "ES|Galicia" to listOf("A Coruna", "Vigo", "Santiago de Compostela"),
    )

    private val pincodeRules: Map<String, Regex> = mapOf(
        "IN" to Regex("^\\d{6}$"),
        "US" to Regex("^\\d{5}(-\\d{4})?$"),
        "GB" to Regex("^[A-Za-z]{1,2}\\d[A-Za-z\\d]? ?\\d[A-Za-z]{2}$"),
        "DE" to Regex("^\\d{5}$"),
        "AU" to Regex("^\\d{4}$"),
        "SG" to Regex("^\\d{6}$"),
        "BR" to Regex("^\\d{5}-?\\d{3}$"),
        "FR" to Regex("^\\d{5}$"),
        "CN" to Regex("^\\d{6}$"),
        "ID" to Regex("^\\d{5}$"),
        "IT" to Regex("^\\d{5}$"),
        "JP" to Regex("^\\d{3}-?\\d{4}$"),
        "MX" to Regex("^\\d{5}$"),
        "NG" to Regex("^\\d{6}$"),
        "SA" to Regex("^\\d{5}$"),
        "ZA" to Regex("^\\d{4}$"),
        "KR" to Regex("^\\d{5}$"),
        "ES" to Regex("^\\d{5}$"),
    )

    fun statesFor(countryCode: String?): List<String> =
        countryCode?.let { statesByCountry[it] } ?: emptyList()

    fun citiesFor(countryCode: String?, state: String?): List<String> {
        if (countryCode == null || state == null) return emptyList()
        return citiesByState["$countryCode|$state"] ?: emptyList()
    }

    /** Country-specific PIN/ZIP validation; countries without a rule accept any non-blank value. */
    fun isValidPincode(countryCode: String?, pin: String): Boolean {
        val trimmed = pin.trim()
        if (trimmed.isEmpty()) return false
        val rule = countryCode?.let { pincodeRules[it] } ?: return true
        return rule.matches(trimmed)
    }
}
